name: Link Check

on:
  pull_request:
    paths:
      - "**/*.md"
      - ".lychee.toml"

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lychee Link Checker
        uses: lycheeverse/lychee-action@v2.0.2
        with:
          args: --config .lychee.toml README.md docs/**/*.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

